name: lightsheet
channels:
  - defaults
dependencies:
  - anyio=2.2.0=py37hecd8cb5_1
  - appnope=0.1.2=py37hecd8cb5_1001
  - argon2-cffi=20.1.0=py37h9ed2024_1
  - async_generator=1.10=py37h28b3542_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - bleach=3.3.0=pyhd3eb1b0_0
  - brotlipy=0.7.0=py37h9ed2024_1003
  - ca-certificates=2021.5.25=hecd8cb5_1
  - certifi=2021.5.30=py37hecd8cb5_0
  - cffi=1.14.0=py37hb5b8e2f_0
  - chardet=4.0.0=py37hecd8cb5_1003
  - cryptography=3.4.7=py37h2fd3fbb_0
  - decorator=5.0.9=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=py37_0
  - idna=2.10=pyhd3eb1b0_0
  - importlib-metadata=3.10.0=py37hecd8cb5_0
  - importlib_metadata=3.10.0=hd3eb1b0_0
  - ipykernel=5.3.4=py37h5ca1d4c_0
  - ipython=7.22.0=py37h01d92e1_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.17.0=py37_0
  - jinja2=3.0.0=pyhd3eb1b0_0
  - json5=0.9.5=py_0
  - jsonschema=3.2.0=py_2
  - jupyter-packaging=0.7.12=pyhd3eb1b0_0
  - jupyter_client=6.1.12=pyhd3eb1b0_0
  - jupyter_core=4.7.1=py37hecd8cb5_0
  - jupyter_server=1.4.1=py37hecd8cb5_0
  - jupyterlab=3.0.14=pyhd3eb1b0_1
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.4.0=pyhd3eb1b0_0
  - libcxx=10.0.0=1
  - libedit=3.1.20210216=h9ed2024_1
  - libffi=3.2.1=h0a44026_1007
  - libsodium=1.0.18=h1de35cc_0
  - markupsafe=2.0.1=py37h9ed2024_0
  - mistune=0.8.4=py37h1de35cc_0
  - nbclassic=0.2.6=pyhd3eb1b0_0
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.0.7=py37_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - ncurses=6.2=h0a44026_1
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - notebook=6.4.0=py37hecd8cb5_0
  - openssl=1.1.1k=h9ed2024_0
  - packaging=20.9=pyhd3eb1b0_0
  - pandoc=2.12=hecd8cb5_0
  - pandocfilters=1.4.3=py37hecd8cb5_1
  - parso=0.8.2=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=21.1.2=py37hecd8cb5_0
  - prometheus_client=0.11.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.17=pyh06a4308_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycparser=2.20=py_2
  - pygments=2.9.0=pyhd3eb1b0_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyrsistent=0.17.3=py37haf1e3a3_0
  - pysocks=1.7.1=py37hecd8cb5_0
  - python=3.7.3=h359304d_0
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - pytz=2021.1=pyhd3eb1b0_0
  - pyzmq=20.0.0=py37h23ab428_1
  - readline=7.0=h1de35cc_5
  - requests=2.25.1=pyhd3eb1b0_0
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=52.0.0=py37hecd8cb5_0
  - six=1.15.0=py37hecd8cb5_0
  - sniffio=1.2.0=py37hecd8cb5_1
  - sqlite=3.33.0=hffcf06c_0
  - terminado=0.9.4=py37hecd8cb5_0
  - testpath=0.4.4=pyhd3eb1b0_0
  - tk=8.6.10=hb0a8c7a_0
  - tornado=6.1=py37h9ed2024_0
  - traitlets=5.0.5=pyhd3eb1b0_0
  - typing_extensions=3.7.4.3=pyha847dfd_0
  - urllib3=1.26.4=pyhd3eb1b0_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py37_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h1de35cc_0
  - zeromq=4.3.4=h23ab428_0
  - zipp=3.4.1=pyhd3eb1b0_0
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - cached-property==1.5.2
    - cycler==0.10.0
    - cython==0.29.23
    - et-xmlfile==1.1.0
    - futures==3.1.1
    - h5py==3.2.1
    - imageio==2.9.0
    - joblib==1.0.1
    - kiwisolver==1.3.1
    - llvmlite==0.36.0
    - matplotlib==3.4.2
    - natsort==7.1.1
    - networkx==2.5.1
    - numba==0.53.1
    - numpy==1.20.3
    - opencv-python==4.5.2.54
    - openpyxl==3.0.7
    - pandas==1.2.4
    - pillow==8.2.0
    - protobuf==3.17.3
    - pywavelets==1.1.1
    - scikit-image==0.18.1
    - scikit-learn==0.24.2
    - scipy==1.6.3
    - seaborn==0.11.1
    - simpleitk==2.0.2
    - tensorboardx==2.2
    - threadpoolctl==2.1.0
    - tifffile==2021.6.6
    - torch==1.8.1
    - torchvision==0.9.1
    - tqdm==4.61.0
    - xlrd==2.0.1
    - xvfbwrapper==0.2.9
prefix: /Users/emilydennis/opt/anaconda3/envs/lightsheet
